export { blue } from "./blue"
export { green } from "./green"
export { gray, grey, white, black } from "./gray"
export { orange } from "./orange"
export { pink } from "./pink"
export { purple } from "./purple"
export { yellow } from "./yellow"
export { red } from "./red"
